---
- name: Pull Docker image of ScientificCalculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Pull image ScientificCalculator
      docker_image:
        name: swastishreya/scientific_calculator:latest
        source: pull
